name: C++ CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation des outils
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ cppcheck
    
    - name: Debug - Liste des fichiers
      run: ls -R  # Cette ligne va afficher tous les fichiers que la CI voit vraiment

    - name: 1. Analyse Statique (Linting)
      run: |
        cppcheck --enable=all \
                 --inline-suppr \
                 --suppress=missingIncludeSystem \
                 --language=c++ \
                 --std=c++17 \
                 --force \
                 --error-exitcode=1 \
                 -I include/ \
                 .

    - name: 2. Configuration CMake
      run: cmake -B build -S .

    - name: 3. Compilation
      run: cmake --build build

    - name: 4. Ex√©cution des Tests
      run: cd build && ctest --output-on-failure